### ISSUE TITLE
Where is the documentation about ISA?

### ISSUE THREAD

**Issue by hlide** [ellisgl/sap-1-v2-mojo#1]
No documentation about ISA means no visibility for this architecture.

**Comment by ellisgl** [comment]
I've been working on it, but here's a ton of "docs" or you can buy "Digital Computer Electronics" by Malvino and Brown.
https://www.google.com/search?q=sap-1+cpu&sa=N&tbm=isch&tbo=u&source=univ&ved=0ahUKEwjzjuCEge7TAhUl3IMKHVCJBZY4ChCwBAgp&biw=1920&bih=960

**Comment by ellisgl** [comment]
I've added some documentation in the README.md

**Comment by ellisgl** [comment]
Is there an official way to show ISA?

**Comment by ellisgl** [comment]
Closing due to lack of respose.
